name: Check

on:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: set up nixpkgs
      uses: cachix/install-nix-action@v31
    - name: Build and check
      run: nix build .#check.nix
